- hosts: terraform-ansible
  tasks: 
  - name: Instalando o python3 e virtualenv
    apt:
      pkg: 
      - python3
      - virtualenv
      update_cache: yes 
    become: yes

    #name: criando arquivo
    #copy: 
    #  dest: /home/ubuntu/index.html
    # content: <h1>Feito com Terraform e Ansible</h1>
  - #name: criando servidor
    #shell: "nohup busybox httpd -f -p 8080 &"